name: Test Scikit-learn Windows with 32-bit Python interpreter

on: push

jobs:
  check:
    name: Check Python 32-bit on Windows
    runs-on: windows-2019
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          - python: '3.9'
          - python: '3.10'
          - python: '3.11'
    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v3
        with:
          repository: glemaitre/scikit-learn
          ref: deprecation_win32

      - name: Install Python 32-bit interpreter
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x86'

      - name: Install Dependencies
        run: pip install numpy scipy==1.9.1 Cython

      - name: Run install
        run: pip install --verbose --no-build-isolation .
